"""empty message

Revision ID: ec66816f971f
Revises: 85b4488d74fb
Create Date: 2019-12-26 14:42:50.334166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec66816f971f'
down_revision = '85b4488d74fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gname', sa.String(length=80), nullable=True),
    sa.Column('gtype', sa.String(length=2), nullable=True),
    sa.Column('gprice', sa.String(length=5), nullable=True),
    sa.Column('gage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gname')
    )
    op.drop_index('gname', table_name='goods')
    op.drop_table('goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gname', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('gtype', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('gage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gprice', mysql.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('gname', 'goods', ['gname'], unique=True)
    op.drop_table('t_goods')
    # ### end Alembic commands ###
